config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :rooms
    resources :reservations
    resources :reviews
  end

  resources :rooms do
    resources :reservations
  end

  resources :reviews, except: %i[edit]
  get '/admin', to: 'admin/homepage#index'
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many :reservations, dependent: :destroy
  validates :number, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true

  mount_uploader :image, ImageUploader
  mount_uploaders :attachments, ImageUploader
end

app/controllers/admin/rooms_controller.rb
# frozen_string_literal: true

module Admin
  class RoomsController < ApplicationController
    before_action :set_admin_room, only: %i[show edit]
    before_action :require_login
    # GET /admin/rooms or /admin/rooms.json
    def index
      @admin_rooms = Room.all
    end

    # GET /admin/rooms/1 or /admin/rooms/1.json
    def show; end

    # GET /admin/rooms/new
    def new
      @admin_room = Room.new
    end

    # GET /admin/rooms/1/edit
    def edit; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_room
      @admin_room = Room.find(params[:id])
    end
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to '/admin/rooms', notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to '/admin/rooms', notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to '/admin/rooms', notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:number, :description, :price, { attachments: [] })
  end
end

app/helpers/admin/rooms_helper.rb
# frozen_string_literal: true

module Admin
  module RoomsHelper
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/admin/rooms/_form.html.erb
<%= form_with(model: admin_room) do |form| %>
  <% if admin_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_room.errors.count, "error") %> prohibited this admin_room from being saved:</h2>

      <ul>
        <% admin_room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>


  <div class="field">
    <%= form.label :attachments %>
    <%= form.file_field :attachments, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/rooms/edit.html.erb
<h1>Editing Admin Room</h1>

<%= render 'form', admin_room: @admin_room %>

<%= link_to 'Show', @admin_room %> |
<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Reviews', admin_reviews_path %>
<%= link_to 'Reservations', admin_reservations_path %>
<h1>Rooms</h1>

<table>
  <thead>
  <tr>

    <th>Number</th>
    <th>Created at</th>
    <th>Updated at</th>

  </tr>
  </thead>

  <tbody>
  <% @admin_rooms.each do |room| %>
    <tr>

      <td><%= room.number %></td>
      <td><%= room.created_at %></td>
      <td><%= room.updated_at %></td>


        <td><%= link_to 'Edit', edit_admin_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_admin_room_path %>

app/views/admin/rooms/new.html.erb
<h1>New Admin Room</h1>

<%= render 'form', admin_room: @admin_room %>

<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @admin_room.number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_room.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @admin_room.image %>
</p>

<%= link_to 'Edit', edit_admin_room_path(@admin_room) %> |
<%= link_to 'Back', admin_rooms_path %>