config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :rooms
    resources :reservations
    resources :reviews
  end

  resources :rooms do
    resources :reservations
  end

  resources :reviews, except: %i[edit]
  get '/admin', to: 'admin/homepage#index'
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :room
end

app/controllers/admin/reservations_controller.rb
# frozen_string_literal: true

module Admin
  class ReservationsController < ApplicationController
    before_action :set_reservation, only: %i[edit update destroy]
    before_action :require_login
    def index
      @reservations = Reservation.all.order(created_at: :desc)
      respond_to do |format|
        format.html
        format.xlsx
      end
    end

    def edit; end

    def update
      respond_to do |format|
        if @reservation.update(reservation_params)
          format.html { redirect_to '/admin/reservations', notice: 'Reservation was successfully confirmed.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @reservation.destroy
      respond_to do |format|
        format.html { redirect_to '/admin/reservations', notice: 'Reservation was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:name, :email, :checkout_date, :checkin_date, :confirmed)
    end
  end
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @reservation = @room.reservations.create(reservation_params)
    redirect_to rooms_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:name, :email, :checkout_date, :checkin_date)
  end
end

app/helpers/admin/reservations_helper.rb
# frozen_string_literal: true

module Admin
  module ReservationsHelper
  end
end

app/helpers/reservations_helper.rb
# frozen_string_literal: true

module ReservationsHelper
end

app/views/admin/reservations/edit.html.erb
<h1>Editing Admin Reservation</h1>

<%= form_for [:admin, @reservation]  do |form| %>

  <p>
    <strong>Room:</strong>
    <%= @reservation.room.number %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= @reservation.name %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= @reservation.email %>
  </p>
  <p>
    <strong>Check-in date:</strong>
    <%= @reservation.checkin_date %>
  </p>
  <p>
    <strong>Check-out date:</strong>
    <%= @reservation.checkout_date %>
  </p>

  <div class="field">
    <%= form.label :confirmed %>
    <%= form.check_box :confirmed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Back', admin_reservations_path %>

app/views/admin/reservations/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Reviews', admin_reviews_path %>
<%= link_to 'Rooms', admin_rooms_path %>
<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Name</th>
      <th>Email</th>
      <th>Check-in date</th>
      <th>Check-out date</th>
      <th>Confirmed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.room.number %></td>
        <td><%= reservation.name %></td>
        <td><%= reservation.email %></td>
        <td><%= reservation.checkin_date %></td>
        <td><%= reservation.checkout_date %></td>
        <td><%= reservation.confirmed %></td>
        <td><%= link_to 'Edit', edit_admin_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', admin_reservation_path(reservation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Download as .xlsx', admin_reservations_path(format: :xlsx) %>