config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :rooms
    resources :reservations
    resources :reviews
  end

  resources :rooms do
    resources :reservations
  end

  resources :reviews, except: %i[edit]
  get '/admin', to: 'admin/homepage#index'
  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

module Admin
  class ReviewsController < ApplicationController
    before_action :set_review, only: %i[edit]
    before_action :require_login
    # GET /admin/reviews or /admin/reviews.json
    def index
      @reviews = Review.all.order(created_at: :desc)
    end

    # GET /admin/reviews/1/edit
    def edit; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit update destroy]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all.where(confirmed: true).order(created_at: :desc)
  end

  # GET /reviews/1 or /reviews/1.json
  def show; end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit; end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to '/reviews', notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      format.html { redirect_to '/admin/reviews', notice: 'Review was successfully updated.' }
      format.json { render :show, status: :ok, location: @review }
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to '/admin/reviews', notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(:author, :email, :review_body, :confirmed)
  end
end

app/helpers/admin/reviews_helper.rb
# frozen_string_literal: true

module Admin
  module ReviewsHelper
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2>All fields must be filled in</h2>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :review_body %>
    <%= form.text_area :review_body %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Rooms', rooms_path %>
<%= link_to 'Home page', root_path %>
<h1>Reviews</h1>

<table>
  <thead>
  <tr>
    <th>Author</th>
    <th>Email</th>
    <th>Review body</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.author %></td>
      <td><%= review.email %></td>
      <td><%= review.review_body %></td>

    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @review.author %>
</p>

<p>
  <strong>Email:</strong>
  <%= @review.email %>
</p>

<p>
  <strong>Review body:</strong>
  <%= @review.review_body %>
</p>


<%= link_to 'Back', reviews_path %>